[build]
  command = "npm run build"
  publish = "build" 
  base = "/"

[images]
  remote_images = ["https://gestion-planning-back-end-0u92.onrender.com/.*"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/public/static/*"
  to = "/public/static/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["axios"]
